### PR TITLE
Fix for persisting user on setting roles

### PR DESCRIPTION
**Pull request by Cluster444**
This saves the roles to an ivar, then after the model is persisted will then persist the roles to the user. Couple of tests that should cover it as well.

stanislaw/simple_roles#3

Signed-off-by: Chris Boertien chris@aktionlab.com

### CODE REVIEW

**Comment by Cluster444** [comment]
not sure why the pull request created a new issue...

**Comment by stanislaw** [comment]
Great thanks for your efforts!

I am working on this as well.

The only thing I am definitely not sure about:

Your current approach assumes not persisting roles only for if `if not persisted?`.

I think issue #3 is more about making `roles=` non-persistent attribute for all kinds of records (new and already) persisted.

Having this said, I think two things are needed to be done to address issue #3 and I am working on them right now:

1) There should be an configuration option like SimpleRoles::Configuration.is_roles_association_attribute_setter_persistent, which should be set to true to provide a compatibility with the way simple roles work currently.

2) If is_roles_association_attribute_setter_persistent is set to false - then `roles=` should always work in a non-persistent manner like any other regular attribute in User model.

I hope I've made a clear explanation of my intentions. If you agree with my thoughts, let me know if you would make corresponding changes and reopen this pull request. If you don't - I am ready to discuss this in details. Thanks again for your work.

**Comment by Cluster444** [comment]
I think the case only applies to a new model situation. In that case you may call User.new then sometime later call save, otherwise your calling create and then it's irrelevant. In an update situation your normally calling update_attributes which is again irrelevant since it's going to call save and expect persistance.

I can't think of too many situations aside from a controler create action with it's new/save combo where I would not want a call to association= to persist as that is what I expect (it's the rails default behavior).

Maybe there are other situations to account for, but I think the best default is whatever rails does, since that will be expected by the most users.

**Comment by stanislaw** [comment]
@Cluster444, your reasoning behind `I think the case only applies to a new model situation.` made me agree with you and think, that I should focus only on "new record case". This way, I achieved the same result, your PR request addresses, by just removing save! from `roles=` method and using your specs - it seems to work just fine.

Please correct me, if I am overlooking something here. 

I didn't do any ruby and rails programming for more than half of a year, so forgive me all this noise about "always non-persistence" and virtual attributes epos.

/cc @Crystark

**Comment by Cluster444** [comment]
That works, i suppose i was overthinking the problem a little bit. I was thinking that rails was doing the saving, but now that I think about it rails already does pretty much exactly what I had implemented. So getting rid of the forced save should make it all behave the way rails folks would expect it to.

**Comment by stanislaw** [comment]
> That works, i suppose i was overthinking the problem a little bit. I was thinking that rails was doing the saving, but now that I think about it rails already does pretty much exactly what I had implemented. So getting rid of the forced save should make it all behave the way rails folks would expect it to.

Exactly! So did I! I am happily closing this, thank you again!

**Pull request closed without merging**
